function generate() {
  const prompt = document.getElementById("prompt");
  const output = document.getElementById("output");

  if (!prompt.value.trim()) {
    output.textContent = "// Enter a vibe to generate something.";
    output.classList.add("show");
    return;
  }

  output.classList.remove("show");

  setTimeout(() => {
    output.textContent =
`// 🚀 Vibe Mode Online

You asked:
"${prompt.value}"

✨ This output will soon be generated by AI.
✨ Motion + UI already activated.`;

    output.classList.add("show");
  }, 300);
}
